### ISSUE TITLE
TypeError: Cannot read property 'EventEmitter' of undefined typescript nodejs

### ISSUE THREAD

**Issue by shaiksyedali** [Gozala/events#64]
I have a typescript application running on node.

I am using 'EventEmitter' class to emit a change in variable value.

This is my piece of code,

```
import events from 'events';

public async updateStream(streamContext: string, state: boolean): Promise<string> {
    const eventEmitter = new events.EventEmitter();
    if (state === true) {
      return StreamManagement.instance.activeStreams.get(streamContext).streamState = 'Paused';
    } else {
      const streamState = StreamManagement.instance.activeStreams.get(streamContext).streamState = 'Active';
      eventEmitter.emit('resume');
      return streamState;
    }
  }

 public async waitForStreamActive(stream: Stream) {
    const eventEmitter = new events.EventEmitter();
    // tslint:disable-next-line:no-unused-expression
    return new Promise(( resolve ) => {
      eventEmitter.on('resume', resolve );
    });
  }
```
This piece of code builds fine. But when i run the code, as in execute the operation, I am getting the following error,

```
error: errorHandler - Apply - Hit Unhandled exception {"timestamp":"2019-04-29T12:33:49.209Z"}
error: errorHandler - Apply - Cannot read property 'EventEmitter' of undefined - TypeError: Cannot read property 'EventEmitter' of undefined
    at StreamResource.updateStream (C:\Vertigo\core\reference_platform\dist\index.js:10695:51)
    at StreamService.patchStream (C:\Vertigo\core\reference_platform\dist\index.js:22524:40)
    at process._tickCallback (internal/process/next_tick.js:68:7) {"timestamp":"2019-04-29T12:33:49.215Z"}
```

What am I doing wrong?

**Comment by vweevers** [comment]
This project is not the `events` module from node core.

That said, you probably want to do `import {EventEmitter} from 'events'`.
